extends:
  - airbnb-base
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:cypress/recommended

plugins:
  - mocha
  - chai-friendly
  - cypress

env:
  node: true
  mocha: true

parserOptions:
  ecmaVersion: 2020
  sourceType: module

rules:
  indent:
    - error
    - 4
    - SwitchCase: 1
  quotes:
    - error
    - single
    - allowTemplateLiterals: true
  semi:
    - error
    - always
  no-console: 0
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
  no-use-before-define:
    - error
    - functions: false
  object-curly-newline:
    - error
    - consistent: true
  object-curly-spacing:
    - error
    - always
  comma-dangle:
    - error
    - always-multiline
  require-await:
    - error
  no-unused-vars:
    - error
    - argsIgnorePattern: next
  prefer-arrow-callback:
    - error
  mocha/no-exclusive-tests: error
  mocha/no-async-describe: error
  mocha/no-nested-tests: error
  mocha/no-top-level-hooks: error
  mocha/max-top-level-suites:
    - warn
    - limit: 1
  no-unused-expressions: 'off'
  chai-friendly/no-unused-expressions: error
