openapi: 3.0.0
info:
  title: Deck of Cards server API
  description: API spec for Deck of Cards app
  version: 0.1.0
paths:
  /api/v1/deck:
    get:
      summary: Get a list of cards from the deck
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Card'
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorInfo'
  /api/v1/deck/shuffle:
    post:
      summary: Shuffle the cards in the deck
      responses:
        204:
          description: Ok
components:
  schemas:
    Card:
      type: string
    ErrorInfo:
      type: object
