openapi: 3.0.0
info:
  title: Deck of Cards server API
  description: API spec for Deck of Cards app
  version: 0.1.0
paths:
  /health:
    get:
      summary: Server is healthy
      responses:
        204:
          description: Ok
  /api/v1/deck:
    get:
      summary: Get the starting deck
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Card'
components:
  schemas:
    Card:
      type: string
